### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by rngwrldngnr** [james-owen-ryan/talktown#2]
I noticed that this repository didn't have any License file. From checking your other repos and seeing that they don't have licenses, but some have instructions for using the code, I thought this might be an oversight. 

Is there a licenses that fits terms you would be comfortable with for using and/or modifying your code?

https://choosealicense.com/no-permission/

**Comment by james-owen-ryan** [comment]
I've just added an MIT license to the repo. Apologies for the lack of clarity!

**Comment by james-owen-ryan** [comment]
I've just added an MIT license to the repo. Apologies for the lack of clarity!
